version: '3'
services:
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
        
  worker:
    image: mpromonet/multisub
    build: .
    command: ["redis://redis"]
    deploy:
      mode: replicated
      replicas: 3
